### ISSUE TITLE
It misreports current download # after retrying

### ISSUE THREAD

**Issue by akr2002** [HelpSeeker/A4A#1]
I ran the script with `python inb4404.py -f https://boards.4channel.org/w/thread/2180153/lain`
The screenshot says it all
![Screenshot_2021-04-09_16-54-35](https://user-images.githubusercontent.com/21287366/114173142-4a6ea580-9954-11eb-92fd-b3ed42027668.png)

**Comment by HelpSeeker** [comment]
Thanks for reporting the issue. My apologies that it took so long for me to fix it. For some reason I didn't have notifications enabled for this repository.
